### ISSUE TITLE
pyopenhc 

### ISSUE THREAD

**Issue by Liujingxiu23** [pengzhendong/g2p_mix#2]
what is pyopenhc , and how to install it ? 

https://github.com/pengzhendong/g2p-mix/blob/master/g2p_mix/g2p_jyut.py#L18

**Comment by pengzhendong** [comment]
https://pypi.org/project/pyopenhc

```bash
$ pip install pyopenhc
```

**Comment by Liujingxiu23** [comment]
Thank you！ running works
